import { KAKAO as KAKAO_CONFIG } from './kakaoKey'

const KAKAO = {
  LOGIN_URL: KAKAO_CONFIG.LOGIN_URL,
  TOKEN_URI: KAKAO_CONFIG.TOKEN_URI,
  USER_INFO_URI: KAKAO_CONFIG.USER_INFO_URI,
  REDIRECT_URI: KAKAO_CONFIG.REDIRECT_URI,
  CLIENT_ID: KAKAO_CONFIG.CLIENT_ID,
  JAVASCRIPT_KEY: KAKAO_CONFIG.JAVASCRIPT_KEY,
}

export { KAKAO }
